#!/usr/bin/perl
use CGI;
use warnings; use strict;
my $cgi = CGI->new();
my %labels = (1=>'sunday', 2=>'monday', 3=>'tuesday', 4=>'wednesday', 5=>'thursday', 6=>'friday', 7=>'saturday');
print $cgi->header(),
$cgi->start_html
(
    -title=>'CGI example',
    -author=>'Steve',
    -meta=>{'keywords'=>'CGI Perl'},
    -BGCOLOR=>'white',
    -LINK=>'red'
    ),
$cgi->center($cgi->img({-src=>'1.jpg'})),
$cgi->center($cgi->h1('Here is the Survey')),
$cgi->h2('Please fill out our survey...'),
"reasons for filling out our survey:",
$cgi->ul
(
    $cgi->li('Fame'),
    $cgi->li('Fortune'),
    $cgi->li('Fun'),
    ),
"If you would rather not fill out our survey, ",
"you might be interested in ",
$cgi->a({href=>'http://www.cpan.org/'}, "CPAN"), ".",
$cgi->hr,
$cgi->start_form
(
    -method=>'POST',
    -action=>'cgi2.pl'
),
"Please enter your name:",
$cgi->textfield('text'),
"Please enter your opinion:",
$cgi->textarea
(
    -name=>'textarea',
    -default=>'No opinion',
    -rows=>10,
    -columns=>60
),
"Please indicate what products you use: ",
$cgi->checkbox_group
(
 -name=>'checkboxes',
 -value=>[qw(shampoo toothpaste bread cruise)],
 -default=>[qw(bread cruise)]
 ),
"please indicate your income level:",
$cgi->scrolling_list
(
    'list',
    [qw(highest high medium low)],
    'high'
),
"please indicate the day of the week:",
$cgi->radio_group
(
 -name=>'radios',
 -value=>[qw(1 2 3 4 5 6 7)],
 -default=>'1',
 -labels=>\%labels
 ),
"please enter your password",
$cgi->hr,
$cgi->end_form,
$cgi->end_html;
